 export const PRODUCT_TYPES = {
    GET_PRODUCTS:"GET_PRODUCTS",
    GET_PRODUCT_DETAILS: "GET_PRODUCT_DETAILS",
    RESET_PRODUCT_DETAILS: "RESET_PRODUCT_DETAILS",
    TOGGLE_LOADER: "TOGGLE_LOADER",
 };